sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iH/Rya3SF9SxF356EKhaCDx6wSE9BVaVZr0AsT+EbLaWLDpVEmDEX3vvDeNdfXgAhMcTA/nFkbwxDFd8BaS3EbTnzGbOcwb6FsnazBlqq3iuf6VW+0n1bpueN8XiII1Lb7fnELuncErG+O2ZFA3h2OjHMNAuD9xkS3oniIuHxByw0LpNhtPJ66uTl7IfDcTj5s1dhBPLitt+fwPciP/610BKhADi/C4CkNyG1U9PFi6csgImjnUD+n+itYLjCQBAMH3e2dq2tNErU0HrGcOtXX+DK/B/J2vNOeEllgoaIaTAKhJ+ti6vYoyzlJv90tpgx+rWvpbnBkL+wVYFfYRoLj91ZkS5FuJLXVFwBTrYcu3UuzxnWC588+bNIhEV+HVBujKXRkxIwlsUPMaES6UkRKAp1oEIzBSuUaodVZ/HAP3ildMhSd1pFopHdKqH+26EXomuF17/NSkxe7G7DEyOlr+J4YBSvAL+BQizdiyJBeiXvF3iKh35wxIH+2FtfhB1N1wrIBZSL+37iI5jlv86BWUKqKmTq+hwR11cFrhC++ylgxjrdDBDJtsKcIgBlyh5Yw8HxdYa65pEetgH3HclhPh1vONeTfPr1GpwKTyCfwIiK6e+Ms7eu1XBelkkLThLCWPymYBqSM23dVTYVeAhW9SfbEAovht6W4rKf0OMi88=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Beetle-A-Mystery_5164
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy